POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Teste",
    "email": "t@t.com",
    "password": "123"
}

###

POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "123"
}